### ISSUE TITLE
Not working as stated

### ISSUE THREAD

**Issue by adpande** [noiseunion/devise-basecamper#1] opened 2012-07-20 17:18 UTC
My environment is 

gem 'rails', '3.2.6'
gem "mongoid", "~> 2.4"
gem "bson_ext"
gem 'devise', "~> 2.1"
gem "devise-basecamper", "~> 0.1"

I am not getting subdomian unique users as stated. I checked all the configuration again and again. But not getting it to work.
Can you please let me know the correct usage. A simple use case will do.

Thanks in advance.

Regards,
Abhishek

**Comment by noiseunion** [comment] 2012-07-30 16:51
I'm setting up a new project to use the basecamper Gem...I'll let you know what I figure out.

**Comment by adpande** [comment] 2012-07-30 16:55
thanks a lot JD

**Comment by noiseunion** [comment] 2012-07-30 17:48
can you please post your user model as well?

**Comment by adpande** [comment] 2012-07-30 17:54
class User
  include Mongoid::Document
  belongs_to :account
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable,:basecamper

```
    # :oauth2_providable, 
    #     :oauth2_password_grantable,
    #     :oauth2_refresh_token_grantable,
    #     :oauth2_authorization_code_grantable
```

  #devise_basecamper :subdomain_class => :account,
   #                 :subdomain_field => :subdomain, 
  #                  :scope_field     => :account_id

  ## Account Relation - if required - added for test
  ## field :account_id,              :type => String

  ## Database authenticatable
    field :email,              :type => String, :default => ""
    field :encrypted_password, :type => String, :default => ""

```
validates_presence_of :email
validates_presence_of :encrypted_password

## Recoverable
field :reset_password_token,   :type => String
field :reset_password_sent_at, :type => Time

## Rememberable
field :remember_created_at, :type => Time

## Trackable
field :sign_in_count,      :type => Integer, :default => 0
field :current_sign_in_at, :type => Time
field :last_sign_in_at,    :type => Time
field :current_sign_in_ip, :type => String
field :last_sign_in_ip,    :type => String

## Confirmable
# field :confirmation_token,   :type => String
# field :confirmed_at,         :type => Time
# field :confirmation_sent_at, :type => Time
# field :unconfirmed_email,    :type => String # Only if using reconfirmable

## Lockable
# field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
# field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
# field :locked_at,       :type => Time

## Token authenticatable
# field :authentication_token, :type => String
# run 'rake db:mongoid:create_indexes' to create indexes
index({ email: 1 }, { unique: true, background: true })
#field :name, :type => String
#validates_presence_of :name
attr_accessible :email, :password, :password_confirmation, :remember_me, :created_at, :updated_at
```

  end

**Comment by adpande** [comment] 2012-07-30 17:55
class Account
  include Mongoid::Document
  has_many :users

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## To handle subdomain
  field :subdomain,              :type => String,:default => "www"
  validates_presence_of :subdomain

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

end

**Comment by noiseunion** [comment] 2012-07-30 18:09
ok, I am updating the README...I think I know what the problem is...and it is me! LOL  I forgot a few steps that need to be done.  Should be posted in a few minutes with a version bump.

**Comment by noiseunion** [comment] 2012-07-30 18:25
I just pushed the update.  LMK if you still have any issues, but I was able to get everything working on a fresh install. :) I'm gonna be offline for a while, but I'll try and check back tonight to make sure you got things working before closing this issue.

**Comment by noiseunion** [comment] 2012-07-30 18:25
oh, the README updates are at the bottom. :)

**Comment by adpande** [comment] 2012-07-30 19:14
Still the user model is not storing the FK (account_id) not sure what is wrong.

**Comment by noiseunion** [comment] 2012-07-30 19:25
Do you have a 'has_many :users' line in your account model? I didn't see one, make sure you put that in.

**Comment by adpande** [comment] 2012-07-30 19:40
yes. I do have that. Check out the 3rd line.

**Comment by noiseunion** [comment] 2012-07-31 00:15
ok, I see it now...missed when looking on my phone. :p  So the problem your experiencing is that the User model is not storing the account id for the parent account?  How are you creating your users?  The problem you're describing isn't going to be caused by the basecamper gem, however it will prohibit it from working properly.

**Comment by noiseunion** [comment] 2012-07-31 00:17
is there any way I can get access to your source code? Is it in Github?

**Comment by noiseunion** [comment] 2012-08-08 02:05
have you had any luck resolving your issue?

**Closed as completed** 2012-08-28 05:35 UTC

**Comment by gaurish** [comment] 2012-12-29 12:34
I faced this issue too.
The issue is that when a new `User` is registered, the `params` hash generated doesn't contain `account_id`, so that's set to `nil`. so the following sql query which runs at login returns nil. Hence, the registered users with valid username/passwords can't login. 

``` SQL
SELECT "users".* FROM "users" WHERE "users"."email" = 'user@example.com' AND "users"."account_id" = 1 LIMIT 1
```

I solved it by overriding Devise's `RegistrationsController`  & manually setting `account_id` on every registration, in following manner:

``` ruby
class RegistrationsController < Devise::RegistrationsController
  def create
    params["user"]["account_id"] = Account.where(subdomain: subdomain).pluck(:id).first
    super
  end
end
```

Thoughts?
